const MessageSchema = {
  name: 'Message',
  primaryKey: '_id',
  properties: {
    _id: 'string',
    createdAt: 'date',
    deletedFor: 'string[]',
    docName: 'string?',
    id: 'string?',
    imageHeight: 'int?',
    imageWidth: 'int?',
    isDeleted: 'bool?',
    iv: 'string?',
    lat: 'double?',
    long: 'double?',
    message: 'string?',
    nonce: 'string?',
    messageTime: 'date?',
    mime: 'string?',
    orientation: 'string?',
    reactions: 'Reaction[]',
    recordTime: 'string?',
    status: 'int?',
    storyImage: 'string?',
    thumbnailImage: 'string?',
    type: 'string',
    updatedAt: 'date?',
    sender: 'string',
    receiver: 'string',
    chatId: 'string?',
    isPlaceholder: 'bool?',
    downloadProgress: 'int?',
    quotedMessage: {type: 'QuotedMessage?', default: null},
    downloadFailed: {type: 'bool?', default: false},
  },
};

const QuotedMessages = {
  name: 'QuotedMessage',
  /// primaryKey: '_id',
  properties: {
    _id: 'string',
    chatId: 'string?',
    createdAt: 'date',
    deletedFor: 'string[]',
    docName: 'string?',
    id: 'string?',
    imageHeight: 'int?',
    imageWidth: 'int?',
    isDeleted: 'bool?',
    iv: 'string?',
    lat: 'double?',
    long: 'double?',
    message: 'string?',
    nonce: 'string?',
    messageTime: 'date?',
    mime: 'string?',
    orientation: 'string?',
    thumbnailImage: 'string?',
    reactions: 'Reaction[]',
    recordTime: 'string?',
    status: 'int?',
    storyImage: 'string?',
    type: 'string',
    updatedAt: 'date?',
    sender: 'string',
    receiver: 'string',
    isPlaceholder: 'bool?',
    downloadProgress: 'int?',
  },
};

const ReactionSchema = {
  name: 'Reaction',
  // primaryKey: '_id',
  properties: {
    _id: 'string',
    type: 'string',
    user: 'string',
    reaction: 'string',
    reactionNew: 'string?',
  },
};

export {MessageSchema, ReactionSchema, QuotedMessages};
