export const CLEAR_DATA = 'CLEAR_DATA';
export const LOADER = 'LOADER';
export const CLEAR_REDUX_STATE = 'CLEAR_REDUX_STATE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const VERIFY_OTP = 'VERIFY_OTP';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

export const RESEND_OTP = 'RESEND_OTP';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';

export const PARTNER_CODE = 'PARTNER_CODE';
export const PARTNER_CODE_SUCCESS = 'PARTNER_CODE_SUCCESS';
export const PARTNER_CODE_FAILURE = 'PARTNER_CODE_FAILURE';

export const RESEND_PARTNER_CODE = 'RESEND_PARTNER_CODE';
export const RESEND_PARTNER_CODE_SUCCESS = 'RESEND_PARTNER_CODE_SUCCESS';
export const RESEND_PARTNER_CODE_FAILURE = 'RESEND_PARTNER_CODE_FAILURE';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';

export const BACKUP = 'BACKUP';
export const BACKUP_SUCCESS = 'BACKUP_SUCCESS';
export const BACKUP_FAILURE = 'BACKUP_FAILURE';

export const DEACTIVATE = 'DEACTIVATE';
export const DEACTIVATE_SUCCESS = 'DEACTIVATE_SUCCESS';
export const DEACTIVATE_FAILURE = 'DEACTIVATE_FAILURE';

export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

export const ENABLE_BIOMETRIC = 'ENABLE_BIOMETRIC';
export const ENABLE_BIOMETRIC_SUCCESS = 'ENABLE_BIOMETRIC_SUCCESS';
export const ENABLE_BIOMETRIC_FAILURE = 'ENABLE_BIOMETRIC_FAILURE';

export const VERIFY_BIOMETRIC = 'VERIFY_BIOMETRIC';
export const VERIFY_BIOMETRIC_SUCCESS = 'VERIFY_BIOMETRIC_SUCCESS';
export const VERIFY_BIOMETRIC_FAILURE = 'VERIFY_BIOMETRIC_FAILURE';

export const ADD_TEMPLATE = 'ADD_TEMPLATE';
export const ADD_TEMPLATE_SUCCESS = 'ADD_TEMPLATE_SUCCESS';
export const ADD_TEMPLATE_FAILURE = 'ADD_TEMPLATE_FAILURE';

export const EDIT_TEMPLATE = 'EDIT_TEMPLATE';
export const EDIT_TEMPLATE_SUCCESS = 'EDIT_TEMPLATE_SUCCESS';
export const EDIT_TEMPLATE_FAILURE = 'EDIT_TEMPLATE_FAILURE';

export const DELETE_TEMPLATE = 'DELETE_TEMPLATE';
export const DELETE_TEMPLATE_SUCCESS = 'DELETE_TEMPLATE_SUCCESS';
export const DELETE_TEMPLATE_FAILURE = 'DELETE_TEMPLATE_FAILURE';

export const GET_TEMPLATES = 'GET_TEMPLATES';
export const GET_TEMPLATES_SUCCESS = 'GET_TEMPLATES_SUCCESS';
export const GET_TEMPLATES_FAILURE = 'GET_TEMPLATES_FAILURE';

export const ADD_TODO_LIST = 'ADD_TODO_LIST';
export const ADD_TODO_LIST_SUCCESS = 'ADD_TODO_LIST_SUCCESS';
export const ADD_TODO_LIST_FAILURE = 'ADD_TODO_LIST_FAILURE';

export const EDIT_TODO_LIST = 'EDIT_TODO_LIST';
export const EDIT_TODO_LIST_SUCCESS = 'EDIT_TODO_LIST_SUCCESS';
export const EDIT_TODO_LIST_FAILURE = 'EDIT_TODO_LIST_FAILURE';

export const DELETE_TODO_LIST = 'DELETE_TODO_LIST';
export const DELETE_TODO_LIST_SUCCESS = 'DELETE_TODO_LIST_SUCCESS';
export const DELETE_TODO_LIST_FAILURE = 'DELETE_TODO_LIST_FAILURE';

export const PIN_UNPIN = 'PIN_UNPIN';
export const PIN_UNPIN_SUCCESS = 'PIN_UNPIN_SUCCESS';
export const PIN_UNPIN_FAILURE = 'PIN_UNPIN_FAILURE';

export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';

export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILURE = 'GET_POST_FAILURE';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';

export const ADD_POST_REACTION_REQUEST = 'ADD_POST_REACTION_REQUEST';
export const ADD_POST_REACTION_SUCCESS = 'ADD_POST_REACTION_SUCCESS';
export const ADD_POST_REACTION_FAILURE = 'ADD_POST_REACTION_FAILURE';

export const ADD_COMMENT_POST_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_POST_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_POST_FAILURE = 'ADD_COMMENT_FAILURE';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

export const DELETE_COMMENT_POST_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_POST_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_POST_FAILURE = 'DELETE_COMMENT_FAILURE';

export const GET_FEELINGS_CHECK = 'GET_FEELINGS_CHECK';
export const GET_FEELINGS_CHECK_SUCCESS = 'GET_FEELINGS_CHECK_SUCCESS';
export const GET_FEELINGS_CHECK_FAILURE = 'GET_FEELINGS_CHECK_FAILURE';

export const ADD_FEELINGS_CHECK = 'ADD_FEELINGS_CHECK';
export const ADD_FEELINGS_CHECK_SUCCESS = 'ADD_FEELINGS_CHECK_SUCCESS';
export const ADD_FEELINGS_CHECK_FAILURE = 'ADD_FEELINGS_CHECK_FAILURE';

export const ADD_ANSWER_QA = 'ADD_ANSWER_QA';
export const ADD_ANSWER_QA_SUCCESS = 'ADD_ANSWER_QA_SUCCESS';
export const ADD_ANSWER_QA_FAILURE = 'ADD_ANSWER_QA_FAILURE';

export const ADD_REACTION = 'ADD_REACTION';
export const ADD_REACTION_SUCCESS = 'ADD_REACTION_SUCCESS';
export const ADD_REACTION_FAILURE = 'ADD_REACTION_FAILURE';

export const DELETE_REACTION = 'DELETE_REACTION';
export const DELETE_REACTION_SUCCESS = 'DELETE_REACTION_SUCCESS';
export const DELETE_REACTION_FAILURE = 'DELETE_REACTION_FAILURE';

export const ADD_NOTE = 'ADD_NOTE';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_FAILURE = 'ADD_NOTE_FAILURE';

export const EDIT_NOTE = 'EDIT_NOTE';
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS';
export const EDIT_NOTE_FAILURE = 'EDIT_NOTE_FAILURE';

export const DELETE_NOTE = 'DELETE_NOTE';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE';

export const GET_ORGANISE_LIST = 'GET_ORGANISE_LIST';
export const GET_ORGANISE_LIST_SUCCESS = 'GET_ORGANISE_LIST_SUCCESS';
export const GET_ORGANISE_LIST_FAILURE = 'GET_ORGANISE_LIST_FAILURE';

export const GET_CHAT = 'GET_CHAT';
export const GET_CHAT_SUCCESS = 'GET_CHAT_SUCCESS';
export const GET_CHAT_FAILURE = 'GET_CHAT_FAILURE';

export const GET_MEDIA = 'GET_MEDIA';
export const GET_MEDIA_SUCCESS = 'GET_MEDIA_SUCCESS';
export const GET_MEDIA_FAILURE = 'GET_MEDIA_FAILURE';

export const GET_LINKS = 'GET_LINKS';
export const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS';
export const GET_LINKS_FAILURE = 'GET_LINKS_FAILURE';

export const DELETE_CHAT = 'DELETE_CHAT';
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS';
export const DELETE_CHAT_FAILURE = 'DELETE_CHAT_FAILURE';

export const GET_CHAT_SEARCH = 'GET_CHAT_SEARCH';
export const GET_CHAT_SEARCH_SUCCESS = 'GET_CHAT_SEARCH_SUCCESS';
export const GET_CHAT_SEARCH_FAILURE = 'GET_CHAT_SEARCH_FAILURE';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const ADD_EVENT = 'ADD_EVENT';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAILURE = 'ADD_EVENT_FAILURE';

export const EDIT_EVENT = 'EDIT_EVENT';
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS';
export const EDIT_EVENT_FAILURE = 'EDIT_EVENT_FAILURE';

export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE';

export const GET_EVENT = 'GET_EVENT';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_FAILURE = 'GET_EVENT_FAILURE';

export const GET_SPECIAL_EVENT = 'GET_SPECIAL_EVENT';
export const GET_SPECIAL_EVENT_SUCCESS = 'GET_SPECIAL_EVENT_SUCCESS';
export const GET_SPECIAL_EVENT_FAILURE = 'GET_SPECIAL_EVENT_FAILURE';

export const ADD_STORY = 'ADD_STORY';
export const ADD_STORY_SUCCESS = 'ADD_STORY_SUCCESS';
export const ADD_STORY_FAILURE = 'ADD_STORY_FAILURE';

export const DELETE_STORY = 'DELETE_STORY';
export const DELETE_STORY_SUCCESS = 'DELETE_STORY_SUCCESS';
export const DELETE_STORY_FAILURE = 'DELETE_STORY_FAILURE';

export const ADD_HIGHLIGHT = 'ADD_HIGHLIGHT';
export const ADD_HIGHLIGHT_SUCCESS = 'ADD_HIGHLIGHT_SUCCESS';
export const ADD_HIGHLIGHT_FAILURE = 'ADD_HIGHLIGHT_FAILURE';

export const REMOVE_HIGHLIGHT = 'REMOVE_HIGHLIGHT';
export const REMOVE_HIGHLIGHT_SUCCESS = 'REMOVE_HIGHLIGHT_SUCCESS';
export const REMOVE_HIGHLIGHT_FAILURE = 'REMOVE_HIGHLIGHT_FAILURE';

export const REMOVE_SINGLE_HIGHLIGHT = 'REMOVE_SINGLE_HIGHLIGHT';
export const REMOVE_SINGLE_HIGHLIGHT_SUCCESS =
  'REMOVE_SINGLE_HIGHLIGHT_SUCCESS';
export const REMOVE_SINGLE_HIGHLIGHT_FAILURE =
  'REMOVE_SINGLE_HIGHLIGHT_FAILURE';

export const GET_STORIES = 'GET_STORIES';
export const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS';
export const GET_STORIES_FAILURE = 'GET_STORIES_FAILURE';

export const GET_HIGHLIGHTS = 'GET_HIGHLIGHTS';
export const GET_HIGHLIGHTS_SUCCESS = 'GET_HIGHLIGHTS_SUCCESS';
export const GET_HIGHLIGHTS_FAILURE = 'GET_HIGHLIGHTS_FAILURE';

export const CREATE_NEW_HIGHLIGHTS = 'CREATE_NEW_HIGHLIGHTS';
export const CREATE_NEW_HIGHLIGHTS_SUCCESS = 'CREATE_NEW_HIGHLIGHTS_SUCCESS';
export const CREATE_NEW_HIGHLIGHTS_FAILURE = 'CREATE_NEW_HIGHLIGHTS_FAILURE';

// Action Types
export const FETCH_MOMENTS_REQUEST = 'FETCH_MOMENTS_REQUEST';
export const FETCH_MOMENTS_SUCCESS = 'FETCH_MOMENTS_SUCCESS';
export const FETCH_MOMENTS_FAILURE = 'FETCH_MOMENTS_FAILURE';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_SPECIAL_EVENTS = 'SET_SPECIAL_EVENTS';
